#!/bin/sh

main() {
    TARBALL="emacs-25.1.tar.gz"
    SRC=$(echo "$TARBALL" | sed 's/\.tar\.gz//')
    URL="https://ftp.gnu.org/gnu/emacs/$TARBALL"
    DLDIR='/tmp/Downloads/'

    if ! isroot; then
	printf "script must be run as root\n"
	exit 1
    fi

    get_build_tools

    mkdir -p "$DLDIR"

    if [ ! -f "$DLDIR$TARBALL" ]; then
	wget "$URL" -P "$DLDIR"
    fi

    if [ -f "$DLDIR$TARBALL" ] && [ ! -d "$DLDIR$SRC" ]; then
	tar xvf "$DLDIR$TARBALL" -C "$DLDIR"
    fi

    if [ -d "$DLDIR$SRC" ]; then
	cd "$DLDIR$SRC"
	./configure --with-x=no
	make
	make install
    else
	printf "could not find %s\n" "$DLDIR$SRC"
    fi

    return 0
}

isroot() {
    if [ $(id -u) -eq 0 ]; then
	return 0
    fi
    return 1
}

get_build_tools(){
    apt -y install build-essential checkinstall
    apt-get -y build-dep emacs24
    return 0
}

main
